version: "3.5"

services:

#  mssql:
    #image: "mcr.microsoft.com/mssql/server:2017-latest"
    #container_name: "mssql"
    #environment:
      #SA_PASSWORD: "Test_Password123"
      #ACCEPT_EULA: "Y"
    #ports:
      #- "1433:1433"
    #restart: always
    #networks:
      #- infrastructure
    #volumes:
      #- "../volumes/mssql:/var/opt/mssql/data"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    networks:
      - infrastructure

  # redis:
  #   image: redis
  #   container_name: "redis"
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   networks:
  #     - infrastructure

  rabbitmq:
    image: "rabbitmq:3.8-management"
    restart: always
    container_name: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "ERLANGCLUSTERCOOKIE"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - infrastructure

networks:
  infrastructure:
    name: infrastructure
    driver: bridge